spring:
  datasource:
    username: root        #======= Need Correct spaces(Tabs) for work this code ######
    password: sahan2004              #====   Space meaning is path #########
    url: jdbc:mysql://localhost:3306/student_crm



         #### One Lined Database URL #######

#spring.datasource.url: mysql://localhost:3306/student_crm

